"""try join with pkey

Revision ID: 1400f64d7729
Revises: 81485936cf29
Create Date: 2022-01-15 16:29:32.643129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1400f64d7729'
down_revision = '81485936cf29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coin_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_trades_symbol_coins', type_='foreignkey')
        batch_op.create_foreign_key('trade_coins_fk', 'coins', ['coin_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_constraint('trade_coins_fk', type_='foreignkey')
        batch_op.create_foreign_key('fk_trades_symbol_coins', 'coins', ['symbol'], ['kucoin_name'])
        batch_op.drop_column('coin_id')

    # ### end Alembic commands ###
